/**
 * searchIndex.ts — Batch project/builder/locality index for autosuggest.
 * Derived from all Batch 1–9 sale data. Used by SmartLocationSearch to
 * surface project and builder names in the dropdown.
 *
 * DO NOT hardcode PSF values here. This is a search index only.
 */

export interface ProjectIndexEntry {
  id: string;
  project: string;
  builder: string;
  locality: string;
  type: "project";
}

// Deduplicated list of all project+builder+locality combos from Batches 1-9
export const BATCH_PROJECT_INDEX: ProjectIndexEntry[] = [
  {
    id: "proj-purple-habiqo",
    project: "Purple Habiqo",
    builder: "Purple Const.",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-onyx-5elem",
    project: "Onyx",
    builder: "5 Elements",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-quiet-earth",
    project: "Quiet Earth T5",
    builder: "Total Environment",
    locality: "Hennur Rd",
    type: "project",
  },
  {
    id: "proj-godrej-ananda",
    project: "Godrej Ananda",
    builder: "Godrej Properties",
    locality: "Bagalur",
    type: "project",
  },
  {
    id: "proj-urbana-aura",
    project: "Urbana Aura",
    builder: "Ozone Group",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-midsummer-rain",
    project: "Midsummer Rain",
    builder: "Axis Capstone",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-popular-ventures",
    project: "Popular Ventures",
    builder: "JCB Dev.",
    locality: "Aduru",
    type: "project",
  },
  {
    id: "proj-sky-sisira",
    project: "Sky Sisira",
    builder: "DS-MAX",
    locality: "Yelahanka",
    type: "project",
  },
  {
    id: "proj-sky-shlokam",
    project: "Sky Shlokam",
    builder: "DS-MAX",
    locality: "Airport Rd",
    type: "project",
  },
  {
    id: "proj-sky-city-dsmax",
    project: "Sky City",
    builder: "DS-MAX",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-karle-zenith",
    project: "Zenith",
    builder: "Karle Infra",
    locality: "Nagavara",
    type: "project",
  },
  {
    id: "proj-lt-raintree",
    project: "Raintree",
    builder: "L&T Realty",
    locality: "Hebbal",
    type: "project",
  },
  {
    id: "proj-karle-vario",
    project: "Vario Homes",
    builder: "Karle Infra",
    locality: "Hebbal",
    type: "project",
  },
  {
    id: "proj-century-breeze",
    project: "Breeze",
    builder: "Century RE",
    locality: "Jakkur",
    type: "project",
  },
  {
    id: "proj-century-greens",
    project: "Century Greens",
    builder: "Century RE",
    locality: "Doddaballapur",
    type: "project",
  },
  {
    id: "proj-hoysala-ace",
    project: "Hoysala Ace",
    builder: "Hoysala Properties",
    locality: "Sahakara NT",
    type: "project",
  },
  {
    id: "proj-sattva-city",
    project: "Sattva City",
    builder: "Sattva Group",
    locality: "Chikkajala",
    type: "project",
  },
  {
    id: "proj-century-sports",
    project: "Century Sports",
    builder: "Century RE",
    locality: "IVC Road",
    type: "project",
  },
  {
    id: "proj-tata-carnatica",
    project: "Carnatica",
    builder: "Tata Housing",
    locality: "Shettigere",
    type: "project",
  },
  {
    id: "proj-earthen-crest",
    project: "Earthen Crest",
    builder: "Sumukha",
    locality: "Gedalahalli",
    type: "project",
  },
  {
    id: "proj-poulomi-florique",
    project: "Florique",
    builder: "Poulomi",
    locality: "Kannur",
    type: "project",
  },
  {
    id: "proj-parthu-pride",
    project: "Parthu Pride",
    builder: "Parthu Build.",
    locality: "Kogilu",
    type: "project",
  },
  {
    id: "proj-earth-soul",
    project: "Earth Soul",
    builder: "Prayuktha Prop.",
    locality: "Hessarghatta",
    type: "project",
  },
  {
    id: "proj-green-gardens",
    project: "Green Gardens",
    builder: "Green Valley",
    locality: "Agrahara",
    type: "project",
  },
  {
    id: "proj-rain-forest",
    project: "Rain Forest",
    builder: "Shriram",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-prestige-raintree",
    project: "Raintree Park",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-prestige-evergreen2",
    project: "Evergreen Ph 2",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-prestige-waterford",
    project: "Waterford",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-dsmax-skyfields",
    project: "Sky Fields",
    builder: "DS-MAX",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-godrej-woodscapes",
    project: "Woodscapes",
    builder: "Godrej Properties",
    locality: "Budigere Cross",
    type: "project",
  },
  {
    id: "proj-sobha-neopolis",
    project: "Neopolis",
    builder: "Sobha Ltd",
    locality: "Panathur",
    type: "project",
  },
  {
    id: "proj-brigade-utopia",
    project: "Utopia",
    builder: "Brigade Group",
    locality: "Varthur",
    type: "project",
  },
  {
    id: "proj-assetz-63east",
    project: "63 East",
    builder: "Assetz Group",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-nambiar-district25",
    project: "District 25",
    builder: "Nambiar",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-prestige-aspen",
    project: "Aspen City",
    builder: "Prestige",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-prestige-great-acres",
    project: "Great Acres",
    builder: "Prestige City",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-adarsh-palm",
    project: "Palm Retreat",
    builder: "Adarsh Dev.",
    locality: "Bellandur",
    type: "project",
  },
  {
    id: "proj-sumadhura-solace",
    project: "Solace",
    builder: "Sumadhura",
    locality: "Marathahalli",
    type: "project",
  },
  {
    id: "proj-brigade-tech-gardens",
    project: "Tech Gardens",
    builder: "Brigade Group",
    locality: "Brookefield",
    type: "project",
  },
  {
    id: "proj-rohan-ekanta",
    project: "Ekanta",
    builder: "Rohan Builders",
    locality: "Gunjur",
    type: "project",
  },
  {
    id: "proj-prestige-park-grove",
    project: "Park Grove",
    builder: "Prestige",
    locality: "Kadugodi",
    type: "project",
  },
  {
    id: "proj-sumadhura-folium",
    project: "Folium",
    builder: "Sumadhura",
    locality: "Varthur",
    type: "project",
  },
  {
    id: "proj-sobha-galera",
    project: "Sobha Galera",
    builder: "Sobha Ltd",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-arvind-skylands",
    project: "Arvind Skylands",
    builder: "Arvind Smartspaces",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-nikoo-homes7",
    project: "Nikoo Homes 7",
    builder: "Bhartiya Urban",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-assetz-soho-sky",
    project: "Soho And Sky",
    builder: "Assetz Group",
    locality: "Jakkur",
    type: "project",
  },
  {
    id: "proj-brigade-northridge",
    project: "Northridge Neo",
    builder: "Brigade Group",
    locality: "Jakkur",
    type: "project",
  },
  {
    id: "proj-lt-raintree-blvd",
    project: "Raintree Blvd",
    builder: "L&T Realty",
    locality: "Hebbal",
    type: "project",
  },
  {
    id: "proj-snn-clermont2",
    project: "Clermont Ph 2",
    builder: "SNN Estates",
    locality: "Nagavara",
    type: "project",
  },
  {
    id: "proj-total-ltf",
    project: "Learning To Fly",
    builder: "Total Environment",
    locality: "Hennur Rd",
    type: "project",
  },
  {
    id: "proj-godrej-woodside",
    project: "Godrej Woodside",
    builder: "Godrej Properties",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-birla-trimaya",
    project: "Trimaya",
    builder: "Birla Estates",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-mims-northstar",
    project: "MIMS Northstar",
    builder: "MIMS Builders",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-brigade-orchards",
    project: "Brigade Orchards",
    builder: "Brigade Group",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-amberstone-ventara",
    project: "Ventara",
    builder: "Amberstone",
    locality: "Chambenahalli",
    type: "project",
  },
  {
    id: "proj-sumadhura-edition",
    project: "Edition",
    builder: "Sumadhura",
    locality: "Nallurhalli",
    type: "project",
  },
  {
    id: "proj-srushti-forest-glade",
    project: "Forest Glade",
    builder: "Srushti Dev.",
    locality: "Hoskote",
    type: "project",
  },
  {
    id: "proj-prestige-camden",
    project: "Camden Gardens",
    builder: "Prestige",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-prestige-windgates",
    project: "Windgates",
    builder: "Prestige",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-prestige-gardenia",
    project: "Gardenia Estates",
    builder: "Prestige",
    locality: "Yelahanka",
    type: "project",
  },
  {
    id: "proj-prestige-park-street",
    project: "Park Street",
    builder: "Prestige",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-godrej-aravya",
    project: "Aravya Estate",
    builder: "Godrej Properties",
    locality: "Doddaballapur",
    type: "project",
  },
  {
    id: "proj-kns-candrill",
    project: "KNS Candrill",
    builder: "KNS",
    locality: "Doddaballapur",
    type: "project",
  },
  {
    id: "proj-ncc-green-province",
    project: "Green Province",
    builder: "NCC Urban",
    locality: "Sompura",
    type: "project",
  },
  {
    id: "proj-abhee-celestial",
    project: "Celestial City",
    builder: "Abhee",
    locality: "Dommasandra",
    type: "project",
  },
  {
    id: "proj-godrej-lakeside",
    project: "Lakeside Orchard",
    builder: "Godrej Properties",
    locality: "Carmelaram",
    type: "project",
  },
  {
    id: "proj-mjr-divine",
    project: "Divine Meadows",
    builder: "MJR Builders",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-abhee-tranquila",
    project: "Abhee Tranquila",
    builder: "Abhee",
    locality: "Attibele Rd",
    type: "project",
  },
  {
    id: "proj-prestige-somerville",
    project: "Somerville",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-prestige-shantiniketan",
    project: "Shantiniketan",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-birla-evara",
    project: "Birla Evara",
    builder: "Birla Estates",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-embassy-springs",
    project: "Embassy Springs",
    builder: "Embassy Group",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-assetz-atmos",
    project: "Atmos And Aura",
    builder: "Assetz Group",
    locality: "Shettigere",
    type: "project",
  },
  {
    id: "proj-sobha-palm-court",
    project: "Palm Court",
    builder: "Sobha Ltd",
    locality: "Yelahanka",
    type: "project",
  },
  {
    id: "proj-coevolve-northern",
    project: "Northern Star",
    builder: "CoEvolve",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-shriram-luxor",
    project: "Luxor",
    builder: "Shriram Properties",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-vajram-tiara",
    project: "Vajram Tiara",
    builder: "Vajram Group",
    locality: "Hennur Rd",
    type: "project",
  },
  {
    id: "proj-prestige-kenilworth",
    project: "Kenilworth",
    builder: "Prestige Group",
    locality: "Hennur Rd",
    type: "project",
  },
  {
    id: "proj-century-seasons",
    project: "Century Seasons",
    builder: "Century RE",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-pushkalam-heritage",
    project: "Heritage",
    builder: "Pushkalam Dev.",
    locality: "Budigere Cross",
    type: "project",
  },
  {
    id: "proj-trifecta-vanto",
    project: "Vanto",
    builder: "Trifecta",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-modern-spaaces-onyx",
    project: "Onyx",
    builder: "Modern Spaaces",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-sobha-silicon",
    project: "Silicon Ph 2",
    builder: "Sobha Ltd",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-total-ite",
    project: "In That Quiet Earth",
    builder: "Total Environment",
    locality: "Hennur Rd",
    type: "project",
  },
  {
    id: "proj-sobha-dream-acres",
    project: "Dream Acres",
    builder: "Sobha Ltd",
    locality: "Varthur",
    type: "project",
  },
  {
    id: "proj-prestige-lavender",
    project: "Lavender Fields",
    builder: "Prestige",
    locality: "Varthur",
    type: "project",
  },
  {
    id: "proj-prestige-eaton",
    project: "Eaton Park",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-prestige-oakville",
    project: "Oakville",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-prestige-avon",
    project: "Avon",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-prestige-pine-forest",
    project: "Pine Forest",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-sobha-sentosa",
    project: "Sentosa",
    builder: "Sobha Ltd",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-tvs-auralis",
    project: "Auralis",
    builder: "TVS Emerald",
    locality: "Yelahanka",
    type: "project",
  },
  {
    id: "proj-casagrand-promenade",
    project: "Promenade",
    builder: "Casagrand",
    locality: "Yelahanka",
    type: "project",
  },
  {
    id: "proj-snn-felicity",
    project: "SNN Felicity Ph 2",
    builder: "SNN Estates",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-bhartiya-nikoo6",
    project: "Nikoo Homes 6",
    builder: "Bhartiya Urban",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-purva-northern-star",
    project: "Purva Northern Star",
    builder: "Puravankara",
    locality: "Hennur",
    type: "project",
  },
  {
    id: "proj-manyata-mango",
    project: "Mango Summers",
    builder: "Manyata",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-brigade-parkside",
    project: "Orchards Parkside",
    builder: "Brigade Group",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-prestige-finsbury",
    project: "Finsbury Regent",
    builder: "Prestige Group",
    locality: "Bagalur",
    type: "project",
  },
  {
    id: "proj-manyata-earthsong",
    project: "Earthsong Ph 2",
    builder: "Manyata",
    locality: "Airport Rd",
    type: "project",
  },
  {
    id: "proj-mantri-energia",
    project: "Energia",
    builder: "Mantri",
    locality: "Nagavara",
    type: "project",
  },
  {
    id: "proj-tata-varnam",
    project: "Tata Varnam",
    builder: "Tata Housing",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-purva-zenium",
    project: "Purva Zenium",
    builder: "Puravankara",
    locality: "Devanahalli",
    type: "project",
  },
  {
    id: "proj-purva-celestial",
    project: "Purva Celestial",
    builder: "Puravankara",
    locality: "Hosahalli",
    type: "project",
  },
  {
    id: "proj-casagrand-orlena",
    project: "Orlena",
    builder: "Casagrand",
    locality: "Gedalahalli",
    type: "project",
  },
  {
    id: "proj-prestige-tranquility",
    project: "Tranquility",
    builder: "Prestige",
    locality: "Budigere Cross",
    type: "project",
  },
  {
    id: "proj-century-sports-ivc",
    project: "Century Sports",
    builder: "Century RE",
    locality: "IVC Road",
    type: "project",
  },
  {
    id: "proj-dsmax-skyvista",
    project: "Sky Vista",
    builder: "DS-MAX",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-dsmax-sky-mansion",
    project: "Sky Mansion",
    builder: "DS-MAX",
    locality: "Hennur Rd",
    type: "project",
  },
  {
    id: "proj-dsmax-sky-grand",
    project: "Sky Grand",
    builder: "DS-MAX",
    locality: "Kalkere",
    type: "project",
  },
  {
    id: "proj-dsmax-sky-aura",
    project: "Sky Aura",
    builder: "DS-MAX",
    locality: "Jakkur",
    type: "project",
  },
  {
    id: "proj-dsmax-sky-sanjeevini",
    project: "Sky Sanjeevini",
    builder: "DS-MAX",
    locality: "Battarahalli",
    type: "project",
  },
  {
    id: "proj-dsmax-sky-shubham",
    project: "Sky Shubham",
    builder: "DS-MAX",
    locality: "KR Puram",
    type: "project",
  },
  {
    id: "proj-sobha-crystal",
    project: "Sobha Crystal",
    builder: "Sobha Ltd",
    locality: "Hennur Rd",
    type: "project",
  },
  {
    id: "proj-prestige-evergreen1",
    project: "Evergreen Ph 1",
    builder: "Prestige",
    locality: "Whitefield",
    type: "project",
  },
  {
    id: "proj-shriram-malhaar",
    project: "Shriram Malhaar",
    builder: "Shriram",
    locality: "Yelahanka",
    type: "project",
  },
  {
    id: "proj-brigade-eldorado",
    project: "El Dorado",
    builder: "Brigade Group",
    locality: "Bagalur",
    type: "project",
  },
  {
    id: "proj-provident-eco",
    project: "Ecopolitan",
    builder: "Provident",
    locality: "Bagalur",
    type: "project",
  },
  {
    id: "proj-bhartiya-nikoo-garden",
    project: "Nikoo Garden Estate",
    builder: "Bhartiya Urban",
    locality: "Sadahalli",
    type: "project",
  },
  {
    id: "proj-concorde-neo",
    project: "Neo",
    builder: "Concorde",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-sobha-dream-gardens",
    project: "Dream Gardens",
    builder: "Sobha Ltd",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-purva-atmosphere",
    project: "Purva Atmosphere",
    builder: "Puravankara",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-kolte-raaga",
    project: "Raaga Ph 2",
    builder: "Kolte Patil",
    locality: "Thanisandra",
    type: "project",
  },
  {
    id: "proj-embassy-blvd",
    project: "Boulevard",
    builder: "Embassy Group",
    locality: "Hebbal",
    type: "project",
  },
  {
    id: "proj-century-horizon",
    project: "Horizon",
    builder: "Century RE",
    locality: "Jakkur",
    type: "project",
  },
  {
    id: "proj-legacy-eldora",
    project: "Legacy Eldora",
    builder: "Legacy Global",
    locality: "Yelahanka",
    type: "project",
  },
  {
    id: "proj-sobha-amber",
    project: "Sobha Amber",
    builder: "Sobha Ltd",
    locality: "Jakkur",
    type: "project",
  },
  {
    id: "proj-brigade-northridge-vista",
    project: "Northridge Vista",
    builder: "Brigade Group",
    locality: "Jakkur",
    type: "project",
  },
  {
    id: "proj-prestige-fairfield",
    project: "Fairfield",
    builder: "Prestige",
    locality: "Hebbal",
    type: "project",
  },
  {
    id: "proj-snn-clermont",
    project: "Clermont",
    builder: "SNN Builders",
    locality: "Hebbal",
    type: "project",
  },
  {
    id: "proj-l-t-raintree-resale",
    project: "Raintree Boulevard",
    builder: "L&T Realty",
    locality: "Hebbal",
    type: "project",
  },
  {
    id: "proj-vajram-vivera",
    project: "Vivera",
    builder: "Vajram",
    locality: "Bagalur",
    type: "project",
  },
  {
    id: "proj-abhee-pride",
    project: "Abhee Pride",
    builder: "Abhee",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-nbr-soul-seasons",
    project: "Soul Seasons",
    builder: "NBR",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-mythri-signature",
    project: "Mythri Signature",
    builder: "Mythri Build.",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-dsr-highland",
    project: "Highland Greenz",
    builder: "DSR Group",
    locality: "Sarjapur Rd",
    type: "project",
  },
  {
    id: "proj-sanjeevini-adwaith",
    project: "The Adwaith",
    builder: "Sanjeevini",
    locality: "Gunjur",
    type: "project",
  },
  {
    id: "proj-dsr-address",
    project: "The Address",
    builder: "DSR Builders",
    locality: "Sarjapur Rd",
    type: "project",
  },
];

/**
 * Fuzzy-search the project index.
 * Returns matching entries with highest relevance first.
 */
function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
    Array.from({ length: n + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0)),
  );
  for (let i = 1; i <= m; i++)
    for (let j = 1; j <= n; j++)
      dp[i][j] =
        a[i - 1] === b[j - 1]
          ? dp[i - 1][j - 1]
          : 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]);
  return dp[m][n];
}

export function searchProjectIndex(query: string): ProjectIndexEntry[] {
  if (!query || query.trim().length < 2) return [];
  const q = query.toLowerCase().trim();
  const scored = BATCH_PROJECT_INDEX.map((entry) => {
    const proj = entry.project.toLowerCase();
    const builder = entry.builder.toLowerCase();
    const loc = entry.locality.toLowerCase();
    let score = 0;
    if (proj === q || builder === q) score = 95;
    else if (proj.startsWith(q) || builder.startsWith(q)) score = 85;
    else if (proj.includes(q) || builder.includes(q) || loc.includes(q))
      score = 72;
    else if (q.length >= 4) {
      const d1 = levenshtein(q, proj.slice(0, q.length + 2));
      const d2 = levenshtein(q, builder.slice(0, q.length + 2));
      if (d1 <= 1 || d2 <= 1) score = 65;
      else if (d1 <= 2 || d2 <= 2) score = 45;
    }
    return { entry, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);
  return scored.slice(0, 6).map((x) => x.entry);
}
