/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AILearningInput {
  'propertyType' : string,
  'area' : number,
  'date' : string,
  'soldPrice' : number,
  'notes' : string,
  'locality' : string,
}
export interface AILearningSubmission {
  'id' : bigint,
  'propertyType' : string,
  'area' : number,
  'date' : string,
  'submittedAt' : bigint,
  'soldPrice' : number,
  'notes' : string,
  'locality' : string,
}
export interface DealScoreResponse {
  'fairValue' : bigint,
  'expectedDaysToSell' : bigint,
  'demandScore' : bigint,
  'liquidityScore' : bigint,
  'dealTag' : string,
  'priceGap' : bigint,
  'dealScore' : bigint,
}
export interface DemandSignal {
  'source' : string,
  'demandScore' : bigint,
  'timestamp' : bigint,
  'locality' : string,
}
export interface Enquiry {
  'id' : bigint,
  'projectName' : string,
  'name' : string,
  'createdAt' : Time,
  'projectId' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface ForecastResponse {
  'conservative' : bigint,
  'aggressive' : bigint,
  'realistic' : bigint,
  'disclaimer' : string,
  'basePrice' : bigint,
  'growthRate' : bigint,
}
export interface Lead {
  'id' : string,
  'service_type' : string,
  'is_priority' : boolean,
  'name' : string,
  'created_at' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
  'budget' : string,
  'location' : string,
  'is_contacted' : boolean,
}
export interface LeadFilter {
  'date_to' : [] | [bigint],
  'service_type' : [] | [string],
  'date_from' : [] | [bigint],
}
export interface LeadInput {
  'service_type' : string,
  'is_priority' : boolean,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'budget' : string,
  'location' : string,
}
export type ListingStatus = { 'published' : null } |
  { 'draft' : null };
export interface LocalityIntelligence {
  'amenitiesScore' : bigint,
  'city' : string,
  'name' : string,
  'avgPricePerSqft' : bigint,
  'demandScore' : bigint,
  'infraScore' : bigint,
  'locationScore' : bigint,
  'rentalPerSqft' : bigint,
  'growthRate' : bigint,
  'supplyDensity' : bigint,
}
export interface ManualProjectEntry {
  'name' : string,
  'submittedAt' : bigint,
  'submittedBy' : string,
  'locality' : string,
}
export interface MetroInfo {
  'nearestStation' : string,
  'distanceKm' : string,
  'hasMetro' : boolean,
  'metroScore' : bigint,
}
export interface PriceSnapshot {
  'source' : string,
  'pricePerSqft' : bigint,
  'confidenceWeight' : bigint,
  'timestamp' : bigint,
  'locality' : string,
}
export interface PropertyListing {
  'id' : bigint,
  'bhk' : bigint,
  'floor' : bigint,
  'status' : ListingStatus,
  'totalFloors' : bigint,
  'title' : string,
  'projectName' : string,
  'propertyType' : PropertyType,
  'city' : string,
  'createdAt' : Time,
  'badges' : Array<string>,
  'carpetArea' : bigint,
  'builderName' : string,
  'builtUpArea' : bigint,
  'description' : string,
  'openParking' : bigint,
  'legalStatus' : string,
  'mediaBlobs' : Array<ExternalBlob>,
  'coveredParking' : bigint,
  'buildingAge' : bigint,
  'sellerId' : Principal,
  'balconies' : bigint,
  'price' : bigint,
  'facing' : string,
  'location' : string,
  'plotArea' : bigint,
  'reraNumber' : string,
  'landUse' : string,
  'plotUnit' : string,
}
export type PropertyType = { 'villa' : null } |
  { 'flat' : null } |
  { 'plot' : null };
export interface RentalResponse {
  'avgRentPerSqft' : bigint,
  'yieldPercent' : bigint,
  'avgRent' : bigint,
  'rentMax' : bigint,
  'rentMin' : bigint,
  'rentalConfidence' : bigint,
  'vacancyRate' : bigint,
}
export interface ReraProject {
  'status' : string,
  'possessionDate' : string,
  'projectName' : string,
  'propertyType' : string,
  'builderName' : string,
  'microLocation' : string,
  'dataType' : string,
  'priceMax' : bigint,
  'priceMin' : bigint,
  'locality' : string,
  'unitSize' : bigint,
}
export interface SaleRecord {
  'propertyType' : string,
  'sqft' : bigint,
  'soldPrice' : bigint,
  'timestamp' : bigint,
  'locality' : string,
}
export interface SalesFeedback {
  'actualPrice' : bigint,
  'predictedPrice' : bigint,
  'timestamp' : bigint,
  'locality' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'password_hash' : [] | [string],
  'username' : string,
  'city' : string,
  'role' : UserRole,
  'fullName' : string,
  'auth_provider' : [] | [string],
  'email' : string,
  'email_hash' : [] | [string],
  'panNumber' : string,
  'subscription_status' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValuationBreakdown {
  'comparablesUsed' : bigint,
  'pricePerSqft' : bigint,
  'infraContribution' : bigint,
  'metroContribution' : bigint,
  'locationContribution' : bigint,
  'demandContribution' : bigint,
  'comparablesContribution' : bigint,
}
export interface ValuationReport {
  'id' : bigint,
  'propertyType' : PropertyType,
  'userId' : Principal,
  'createdAt' : Time,
  'estimatedMax' : bigint,
  'estimatedMin' : bigint,
  'confidence' : bigint,
  'location' : string,
}
export interface ValuationResponse {
  'breakdown' : ValuationBreakdown,
  'confidenceReason' : string,
  'bestPrice' : bigint,
  'priceMax' : bigint,
  'priceMin' : bigint,
  'confidence' : bigint,
  'localityFound' : boolean,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addNewReraProjects' : ActorMethod<[Array<ReraProject>], boolean>,
  'addPriceSnapshot' : ActorMethod<[string, bigint], string>,
  'addValuationReport' : ActorMethod<
    [string, PropertyType, bigint, bigint, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupOldData' : ActorMethod<[bigint], string>,
  'computeValuation' : ActorMethod<
    [string, string, bigint, bigint, bigint],
    ValuationResponse
  >,
  'createCheckoutSession' : ActorMethod<[], string>,
  'createEnquiry' : ActorMethod<[string, string, string, string], bigint>,
  'createListing' : ActorMethod<
    [
      string,
      PropertyType,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      Array<string>,
      Array<ExternalBlob>,
      string,
    ],
    bigint
  >,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'filterListings' : ActorMethod<
    [PropertyType, bigint, bigint, bigint],
    Array<PropertyListing>
  >,
  'getAILearningSubmissions' : ActorMethod<[], Array<AILearningSubmission>>,
  'getAllPublishedListings' : ActorMethod<[], Array<PropertyListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDealScore' : ActorMethod<[bigint], DealScoreResponse>,
  'getDemandSignals' : ActorMethod<[string], Array<DemandSignal>>,
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getFeedbackCount' : ActorMethod<[], bigint>,
  'getForecast' : ActorMethod<[string, string], ForecastResponse>,
  'getLeads' : ActorMethod<[LeadFilter], Array<Lead>>,
  'getListingById' : ActorMethod<[bigint], [] | [PropertyListing]>,
  'getListingsBySeller' : ActorMethod<[Principal], Array<PropertyListing>>,
  'getLocalityIntelligence' : ActorMethod<
    [string],
    [] | [LocalityIntelligence]
  >,
  'getLocalityList' : ActorMethod<[], Array<string>>,
  'getManualProjects' : ActorMethod<[string], Array<ManualProjectEntry>>,
  'getMetroInfo' : ActorMethod<[string], MetroInfo>,
  'getPriceHistory' : ActorMethod<[string], Array<PriceSnapshot>>,
  'getRentalIntelligence' : ActorMethod<[string], RentalResponse>,
  'getReraProjects' : ActorMethod<[], Array<ReraProject>>,
  'getSaleRecords' : ActorMethod<[], Array<SaleRecord>>,
  'getSalesFeedbackLog' : ActorMethod<[], Array<SalesFeedback>>,
  'getSavedProperties' : ActorMethod<[], Array<PropertyListing>>,
  'getStripeSessionStatus' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscriptionStatus' : ActorMethod<[], string>,
  'getValuationReportsForUser' : ActorMethod<
    [Principal],
    Array<ValuationReport>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isIntelligenceSeeded' : ActorMethod<[], boolean>,
  'isPremiumUser' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'loginWithEmail' : ActorMethod<[string, string], [] | [UserProfile]>,
  'markLeadContacted' : ActorMethod<[string], boolean>,
  'publishListing' : ActorMethod<[bigint], undefined>,
  'recordDailySnapshot' : ActorMethod<[string], string>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'registerWithEmail' : ActorMethod<[string, string, string], string>,
  'runValidationTests' : ActorMethod<[], Array<string>>,
  'saveAILearningSubmission' : ActorMethod<[AILearningInput], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProperty' : ActorMethod<[bigint], undefined>,
  'searchListings' : ActorMethod<[string], Array<PropertyListing>>,
  'searchLocalities' : ActorMethod<[string], Array<string>>,
  'seedAndRetrain' : ActorMethod<[Array<ReraProject>], boolean>,
  'seedIntelligenceData' : ActorMethod<[], undefined>,
  'setStripeConfig' : ActorMethod<[string, bigint, Array<string>], undefined>,
  'setStripeConfiguration' : ActorMethod<
    [string, bigint, Array<string>],
    undefined
  >,
  'submitLead' : ActorMethod<[LeadInput], string>,
  'submitManualProject' : ActorMethod<[string, string], undefined>,
  'submitSaleFeedback' : ActorMethod<[string, bigint, bigint], string>,
  'submitSaleRecord' : ActorMethod<[string, bigint, string, bigint], string>,
  'trackFeedback' : ActorMethod<[bigint, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unsaveProperty' : ActorMethod<[bigint], undefined>,
  'updateConfidence' : ActorMethod<[string, string, bigint], string>,
  'updateDemandSignals' : ActorMethod<[], string>,
  'updateListing' : ActorMethod<
    [
      bigint,
      string,
      PropertyType,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      Array<string>,
      Array<ExternalBlob>,
      string,
    ],
    undefined
  >,
  'updateReraProject' : ActorMethod<
    [string, string, string, bigint, bigint],
    boolean
  >,
  'updateSubscriptionStatus' : ActorMethod<[string, string], boolean>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'verifyAndUpgradeFromSession' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];