/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ReraProject = IDL.Record({
  'status' : IDL.Text,
  'possessionDate' : IDL.Text,
  'projectName' : IDL.Text,
  'propertyType' : IDL.Text,
  'builderName' : IDL.Text,
  'microLocation' : IDL.Text,
  'dataType' : IDL.Text,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'locality' : IDL.Text,
  'unitSize' : IDL.Nat,
});
export const PropertyType = IDL.Variant({
  'villa' : IDL.Null,
  'flat' : IDL.Null,
  'plot' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ValuationBreakdown = IDL.Record({
  'comparablesUsed' : IDL.Nat,
  'pricePerSqft' : IDL.Nat,
  'infraContribution' : IDL.Nat,
  'metroContribution' : IDL.Nat,
  'locationContribution' : IDL.Nat,
  'demandContribution' : IDL.Nat,
  'comparablesContribution' : IDL.Nat,
});
export const ValuationResponse = IDL.Record({
  'breakdown' : ValuationBreakdown,
  'confidenceReason' : IDL.Text,
  'bestPrice' : IDL.Nat,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'confidence' : IDL.Nat,
  'localityFound' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const PropertyListing = IDL.Record({
  'id' : IDL.Nat,
  'bhk' : IDL.Nat,
  'floor' : IDL.Nat,
  'status' : ListingStatus,
  'totalFloors' : IDL.Nat,
  'title' : IDL.Text,
  'projectName' : IDL.Text,
  'propertyType' : PropertyType,
  'city' : IDL.Text,
  'createdAt' : Time,
  'badges' : IDL.Vec(IDL.Text),
  'carpetArea' : IDL.Nat,
  'builderName' : IDL.Text,
  'builtUpArea' : IDL.Nat,
  'description' : IDL.Text,
  'openParking' : IDL.Nat,
  'legalStatus' : IDL.Text,
  'mediaBlobs' : IDL.Vec(ExternalBlob),
  'coveredParking' : IDL.Nat,
  'buildingAge' : IDL.Nat,
  'sellerId' : IDL.Principal,
  'balconies' : IDL.Nat,
  'price' : IDL.Nat,
  'facing' : IDL.Text,
  'location' : IDL.Text,
  'plotArea' : IDL.Nat,
  'reraNumber' : IDL.Text,
  'landUse' : IDL.Text,
  'plotUnit' : IDL.Text,
});
export const AILearningSubmission = IDL.Record({
  'id' : IDL.Nat,
  'propertyType' : IDL.Text,
  'area' : IDL.Float64,
  'date' : IDL.Text,
  'submittedAt' : IDL.Int,
  'soldPrice' : IDL.Float64,
  'notes' : IDL.Text,
  'locality' : IDL.Text,
});
export const BankerStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BankerApplication = IDL.Record({
  'id' : IDL.Nat,
  'org' : IDL.Text,
  'status' : BankerStatus,
  'appliedAt' : IDL.Int,
  'principal' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'reviewNote' : IDL.Text,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'password_hash' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'city' : IDL.Text,
  'role' : UserRole,
  'fullName' : IDL.Text,
  'auth_provider' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'email_hash' : IDL.Opt(IDL.Text),
  'panNumber' : IDL.Text,
  'subscription_status' : IDL.Text,
  'mobile' : IDL.Text,
});
export const DealScoreResponse = IDL.Record({
  'fairValue' : IDL.Nat,
  'expectedDaysToSell' : IDL.Nat,
  'demandScore' : IDL.Nat,
  'liquidityScore' : IDL.Nat,
  'dealTag' : IDL.Text,
  'priceGap' : IDL.Int,
  'dealScore' : IDL.Nat,
});
export const DemandSignal = IDL.Record({
  'source' : IDL.Text,
  'demandScore' : IDL.Nat,
  'timestamp' : IDL.Int,
  'locality' : IDL.Text,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'projectName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'projectId' : IDL.Text,
  'phone' : IDL.Text,
});
export const ForecastResponse = IDL.Record({
  'conservative' : IDL.Nat,
  'aggressive' : IDL.Nat,
  'realistic' : IDL.Nat,
  'disclaimer' : IDL.Text,
  'basePrice' : IDL.Nat,
  'growthRate' : IDL.Nat,
});
export const LeadFilter = IDL.Record({
  'date_to' : IDL.Opt(IDL.Int),
  'service_type' : IDL.Opt(IDL.Text),
  'date_from' : IDL.Opt(IDL.Int),
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'service_type' : IDL.Text,
  'is_priority' : IDL.Bool,
  'name' : IDL.Text,
  'created_at' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'budget' : IDL.Text,
  'location' : IDL.Text,
  'is_contacted' : IDL.Bool,
});
export const LocalityIntelligence = IDL.Record({
  'amenitiesScore' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'avgPricePerSqft' : IDL.Nat,
  'demandScore' : IDL.Nat,
  'infraScore' : IDL.Nat,
  'locationScore' : IDL.Nat,
  'rentalPerSqft' : IDL.Nat,
  'growthRate' : IDL.Nat,
  'supplyDensity' : IDL.Nat,
});
export const ManualProjectEntry = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Text,
  'locality' : IDL.Text,
});
export const MetroInfo = IDL.Record({
  'nearestStation' : IDL.Text,
  'distanceKm' : IDL.Text,
  'hasMetro' : IDL.Bool,
  'metroScore' : IDL.Nat,
});
export const PriceSnapshot = IDL.Record({
  'source' : IDL.Text,
  'pricePerSqft' : IDL.Nat,
  'confidenceWeight' : IDL.Nat,
  'timestamp' : IDL.Int,
  'locality' : IDL.Text,
});
export const RentalResponse = IDL.Record({
  'avgRentPerSqft' : IDL.Nat,
  'yieldPercent' : IDL.Nat,
  'avgRent' : IDL.Nat,
  'rentMax' : IDL.Nat,
  'rentMin' : IDL.Nat,
  'rentalConfidence' : IDL.Nat,
  'vacancyRate' : IDL.Nat,
});
export const SaleRecord = IDL.Record({
  'propertyType' : IDL.Text,
  'sqft' : IDL.Nat,
  'soldPrice' : IDL.Nat,
  'timestamp' : IDL.Int,
  'locality' : IDL.Text,
});
export const SalesFeedback = IDL.Record({
  'actualPrice' : IDL.Nat,
  'predictedPrice' : IDL.Nat,
  'timestamp' : IDL.Int,
  'locality' : IDL.Text,
});
export const ValuationReport = IDL.Record({
  'id' : IDL.Nat,
  'propertyType' : PropertyType,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'estimatedMax' : IDL.Nat,
  'estimatedMin' : IDL.Nat,
  'confidence' : IDL.Nat,
  'location' : IDL.Text,
});
export const AILearningInput = IDL.Record({
  'propertyType' : IDL.Text,
  'area' : IDL.Float64,
  'date' : IDL.Text,
  'soldPrice' : IDL.Float64,
  'notes' : IDL.Text,
  'locality' : IDL.Text,
});
export const LeadInput = IDL.Record({
  'service_type' : IDL.Text,
  'is_priority' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'budget' : IDL.Text,
  'location' : IDL.Text,
});
export const ApartmentSubType = IDL.Variant({
  'township' : IDL.Null,
  'gated' : IDL.Null,
  'standalone' : IDL.Null,
  'unknown' : IDL.Null,
});
export const ValuationRequest = IDL.Record({
  'age' : IDL.Nat,
  'propertyType' : IDL.Text,
  'sqft' : IDL.Nat,
  'builderName' : IDL.Opt(IDL.Text),
  'apartmentSubType' : IDL.Opt(ApartmentSubType),
  'locality' : IDL.Text,
  'amenitiesCount' : IDL.Nat,
});
export const ValuationResult = IDL.Record({
  'comparablesUsed' : IDL.Nat,
  'subTypeMultiplier' : IDL.Nat,
  'pricePerSqft' : IDL.Nat,
  'infraContribution' : IDL.Nat,
  'metroContribution' : IDL.Nat,
  'locationContribution' : IDL.Nat,
  'confidenceReason' : IDL.Text,
  'subTypeApplied' : IDL.Text,
  'builderApplied' : IDL.Text,
  'demandContribution' : IDL.Nat,
  'bestPrice' : IDL.Nat,
  'comparablesContribution' : IDL.Nat,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'confidence' : IDL.Nat,
  'localityFound' : IDL.Bool,
  'builderMultiplier' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addNewReraProjects' : IDL.Func([IDL.Vec(ReraProject)], [IDL.Bool], []),
  'addPriceSnapshot' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'addValuationReport' : IDL.Func(
      [IDL.Text, PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'approveBankOfficer' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupOldData' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'computeValuation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [ValuationResponse],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func([], [IDL.Text], []),
  'createEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'filterListings' : IDL.Func(
      [PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getAILearningSubmissions' : IDL.Func(
      [],
      [IDL.Vec(AILearningSubmission)],
      ['query'],
    ),
  'getAllBankerApps' : IDL.Func([], [IDL.Vec(BankerApplication)], ['query']),
  'getAllPublishedListings' : IDL.Func(
      [],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDealScore' : IDL.Func([IDL.Nat], [DealScoreResponse], ['query']),
  'getDemandSignals' : IDL.Func([IDL.Text], [IDL.Vec(DemandSignal)], ['query']),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getFeedbackCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getForecast' : IDL.Func([IDL.Text, IDL.Text], [ForecastResponse], ['query']),
  'getLeads' : IDL.Func([LeadFilter], [IDL.Vec(Lead)], ['query']),
  'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(PropertyListing)], ['query']),
  'getListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getLocalityIntelligence' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LocalityIntelligence)],
      ['query'],
    ),
  'getLocalityList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getManualProjects' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ManualProjectEntry)],
      ['query'],
    ),
  'getMetroInfo' : IDL.Func([IDL.Text], [MetroInfo], ['query']),
  'getMyBankerStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getPendingBankers' : IDL.Func([], [IDL.Vec(BankerApplication)], ['query']),
  'getPriceHistory' : IDL.Func([IDL.Text], [IDL.Vec(PriceSnapshot)], ['query']),
  'getRentalIntelligence' : IDL.Func([IDL.Text], [RentalResponse], ['query']),
  'getReraProjects' : IDL.Func([], [IDL.Vec(ReraProject)], ['query']),
  'getSaleRecords' : IDL.Func([], [IDL.Vec(SaleRecord)], ['query']),
  'getSalesFeedbackLog' : IDL.Func([], [IDL.Vec(SalesFeedback)], ['query']),
  'getSavedProperties' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscriptionStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getValuationReportsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ValuationReport)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isIntelligenceSeeded' : IDL.Func([], [IDL.Bool], ['query']),
  'isPremiumUser' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithEmail' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'markLeadContacted' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'publishListing' : IDL.Func([IDL.Nat], [], []),
  'recordDailySnapshot' : IDL.Func([IDL.Text], [IDL.Text], []),
  'registerBankOfficer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'registerWithEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'rejectBankOfficer' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'runValidationTests' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveAILearningSubmission' : IDL.Func([AILearningInput], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProperty' : IDL.Func([IDL.Nat], [], []),
  'searchListings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'searchLocalities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'seedAndRetrain' : IDL.Func([IDL.Vec(ReraProject)], [IDL.Bool], []),
  'seedIntelligenceData' : IDL.Func([], [], []),
  'setStripeConfig' : IDL.Func([IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'setStripeConfiguration' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'submitLead' : IDL.Func([LeadInput], [IDL.Text], []),
  'submitManualProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitSaleFeedback' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Text], []),
  'submitSaleRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'submitValuation' : IDL.Func(
      [ValuationRequest],
      [ValuationResult],
      ['query'],
    ),
  'trackFeedback' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unsaveProperty' : IDL.Func([IDL.Nat], [], []),
  'updateConfidence' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'updateDemandSignals' : IDL.Func([], [IDL.Text], []),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateReraProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateSubscriptionStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'verifyAndUpgradeFromSession' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ReraProject = IDL.Record({
    'status' : IDL.Text,
    'possessionDate' : IDL.Text,
    'projectName' : IDL.Text,
    'propertyType' : IDL.Text,
    'builderName' : IDL.Text,
    'microLocation' : IDL.Text,
    'dataType' : IDL.Text,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'locality' : IDL.Text,
    'unitSize' : IDL.Nat,
  });
  const PropertyType = IDL.Variant({
    'villa' : IDL.Null,
    'flat' : IDL.Null,
    'plot' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ValuationBreakdown = IDL.Record({
    'comparablesUsed' : IDL.Nat,
    'pricePerSqft' : IDL.Nat,
    'infraContribution' : IDL.Nat,
    'metroContribution' : IDL.Nat,
    'locationContribution' : IDL.Nat,
    'demandContribution' : IDL.Nat,
    'comparablesContribution' : IDL.Nat,
  });
  const ValuationResponse = IDL.Record({
    'breakdown' : ValuationBreakdown,
    'confidenceReason' : IDL.Text,
    'bestPrice' : IDL.Nat,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'confidence' : IDL.Nat,
    'localityFound' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const PropertyListing = IDL.Record({
    'id' : IDL.Nat,
    'bhk' : IDL.Nat,
    'floor' : IDL.Nat,
    'status' : ListingStatus,
    'totalFloors' : IDL.Nat,
    'title' : IDL.Text,
    'projectName' : IDL.Text,
    'propertyType' : PropertyType,
    'city' : IDL.Text,
    'createdAt' : Time,
    'badges' : IDL.Vec(IDL.Text),
    'carpetArea' : IDL.Nat,
    'builderName' : IDL.Text,
    'builtUpArea' : IDL.Nat,
    'description' : IDL.Text,
    'openParking' : IDL.Nat,
    'legalStatus' : IDL.Text,
    'mediaBlobs' : IDL.Vec(ExternalBlob),
    'coveredParking' : IDL.Nat,
    'buildingAge' : IDL.Nat,
    'sellerId' : IDL.Principal,
    'balconies' : IDL.Nat,
    'price' : IDL.Nat,
    'facing' : IDL.Text,
    'location' : IDL.Text,
    'plotArea' : IDL.Nat,
    'reraNumber' : IDL.Text,
    'landUse' : IDL.Text,
    'plotUnit' : IDL.Text,
  });
  const AILearningSubmission = IDL.Record({
    'id' : IDL.Nat,
    'propertyType' : IDL.Text,
    'area' : IDL.Float64,
    'date' : IDL.Text,
    'submittedAt' : IDL.Int,
    'soldPrice' : IDL.Float64,
    'notes' : IDL.Text,
    'locality' : IDL.Text,
  });
  const BankerStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BankerApplication = IDL.Record({
    'id' : IDL.Nat,
    'org' : IDL.Text,
    'status' : BankerStatus,
    'appliedAt' : IDL.Int,
    'principal' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'reviewNote' : IDL.Text,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'password_hash' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'city' : IDL.Text,
    'role' : UserRole,
    'fullName' : IDL.Text,
    'auth_provider' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'email_hash' : IDL.Opt(IDL.Text),
    'panNumber' : IDL.Text,
    'subscription_status' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const DealScoreResponse = IDL.Record({
    'fairValue' : IDL.Nat,
    'expectedDaysToSell' : IDL.Nat,
    'demandScore' : IDL.Nat,
    'liquidityScore' : IDL.Nat,
    'dealTag' : IDL.Text,
    'priceGap' : IDL.Int,
    'dealScore' : IDL.Nat,
  });
  const DemandSignal = IDL.Record({
    'source' : IDL.Text,
    'demandScore' : IDL.Nat,
    'timestamp' : IDL.Int,
    'locality' : IDL.Text,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'projectName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'projectId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ForecastResponse = IDL.Record({
    'conservative' : IDL.Nat,
    'aggressive' : IDL.Nat,
    'realistic' : IDL.Nat,
    'disclaimer' : IDL.Text,
    'basePrice' : IDL.Nat,
    'growthRate' : IDL.Nat,
  });
  const LeadFilter = IDL.Record({
    'date_to' : IDL.Opt(IDL.Int),
    'service_type' : IDL.Opt(IDL.Text),
    'date_from' : IDL.Opt(IDL.Int),
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'service_type' : IDL.Text,
    'is_priority' : IDL.Bool,
    'name' : IDL.Text,
    'created_at' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'budget' : IDL.Text,
    'location' : IDL.Text,
    'is_contacted' : IDL.Bool,
  });
  const LocalityIntelligence = IDL.Record({
    'amenitiesScore' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'avgPricePerSqft' : IDL.Nat,
    'demandScore' : IDL.Nat,
    'infraScore' : IDL.Nat,
    'locationScore' : IDL.Nat,
    'rentalPerSqft' : IDL.Nat,
    'growthRate' : IDL.Nat,
    'supplyDensity' : IDL.Nat,
  });
  const ManualProjectEntry = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Text,
    'locality' : IDL.Text,
  });
  const MetroInfo = IDL.Record({
    'nearestStation' : IDL.Text,
    'distanceKm' : IDL.Text,
    'hasMetro' : IDL.Bool,
    'metroScore' : IDL.Nat,
  });
  const PriceSnapshot = IDL.Record({
    'source' : IDL.Text,
    'pricePerSqft' : IDL.Nat,
    'confidenceWeight' : IDL.Nat,
    'timestamp' : IDL.Int,
    'locality' : IDL.Text,
  });
  const RentalResponse = IDL.Record({
    'avgRentPerSqft' : IDL.Nat,
    'yieldPercent' : IDL.Nat,
    'avgRent' : IDL.Nat,
    'rentMax' : IDL.Nat,
    'rentMin' : IDL.Nat,
    'rentalConfidence' : IDL.Nat,
    'vacancyRate' : IDL.Nat,
  });
  const SaleRecord = IDL.Record({
    'propertyType' : IDL.Text,
    'sqft' : IDL.Nat,
    'soldPrice' : IDL.Nat,
    'timestamp' : IDL.Int,
    'locality' : IDL.Text,
  });
  const SalesFeedback = IDL.Record({
    'actualPrice' : IDL.Nat,
    'predictedPrice' : IDL.Nat,
    'timestamp' : IDL.Int,
    'locality' : IDL.Text,
  });
  const ValuationReport = IDL.Record({
    'id' : IDL.Nat,
    'propertyType' : PropertyType,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'estimatedMax' : IDL.Nat,
    'estimatedMin' : IDL.Nat,
    'confidence' : IDL.Nat,
    'location' : IDL.Text,
  });
  const AILearningInput = IDL.Record({
    'propertyType' : IDL.Text,
    'area' : IDL.Float64,
    'date' : IDL.Text,
    'soldPrice' : IDL.Float64,
    'notes' : IDL.Text,
    'locality' : IDL.Text,
  });
  const LeadInput = IDL.Record({
    'service_type' : IDL.Text,
    'is_priority' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'budget' : IDL.Text,
    'location' : IDL.Text,
  });
  const ApartmentSubType = IDL.Variant({
    'township' : IDL.Null,
    'gated' : IDL.Null,
    'standalone' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const ValuationRequest = IDL.Record({
    'age' : IDL.Nat,
    'propertyType' : IDL.Text,
    'sqft' : IDL.Nat,
    'builderName' : IDL.Opt(IDL.Text),
    'apartmentSubType' : IDL.Opt(ApartmentSubType),
    'locality' : IDL.Text,
    'amenitiesCount' : IDL.Nat,
  });
  const ValuationResult = IDL.Record({
    'comparablesUsed' : IDL.Nat,
    'subTypeMultiplier' : IDL.Nat,
    'pricePerSqft' : IDL.Nat,
    'infraContribution' : IDL.Nat,
    'metroContribution' : IDL.Nat,
    'locationContribution' : IDL.Nat,
    'confidenceReason' : IDL.Text,
    'subTypeApplied' : IDL.Text,
    'builderApplied' : IDL.Text,
    'demandContribution' : IDL.Nat,
    'bestPrice' : IDL.Nat,
    'comparablesContribution' : IDL.Nat,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'confidence' : IDL.Nat,
    'localityFound' : IDL.Bool,
    'builderMultiplier' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addNewReraProjects' : IDL.Func([IDL.Vec(ReraProject)], [IDL.Bool], []),
    'addPriceSnapshot' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'addValuationReport' : IDL.Func(
        [IDL.Text, PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'approveBankOfficer' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupOldData' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'computeValuation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [ValuationResponse],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func([], [IDL.Text], []),
    'createEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'filterListings' : IDL.Func(
        [PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getAILearningSubmissions' : IDL.Func(
        [],
        [IDL.Vec(AILearningSubmission)],
        ['query'],
      ),
    'getAllBankerApps' : IDL.Func([], [IDL.Vec(BankerApplication)], ['query']),
    'getAllPublishedListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDealScore' : IDL.Func([IDL.Nat], [DealScoreResponse], ['query']),
    'getDemandSignals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DemandSignal)],
        ['query'],
      ),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getFeedbackCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getForecast' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ForecastResponse],
        ['query'],
      ),
    'getLeads' : IDL.Func([LeadFilter], [IDL.Vec(Lead)], ['query']),
    'getListingById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PropertyListing)],
        ['query'],
      ),
    'getListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getLocalityIntelligence' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LocalityIntelligence)],
        ['query'],
      ),
    'getLocalityList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getManualProjects' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ManualProjectEntry)],
        ['query'],
      ),
    'getMetroInfo' : IDL.Func([IDL.Text], [MetroInfo], ['query']),
    'getMyBankerStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getPendingBankers' : IDL.Func([], [IDL.Vec(BankerApplication)], ['query']),
    'getPriceHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PriceSnapshot)],
        ['query'],
      ),
    'getRentalIntelligence' : IDL.Func([IDL.Text], [RentalResponse], ['query']),
    'getReraProjects' : IDL.Func([], [IDL.Vec(ReraProject)], ['query']),
    'getSaleRecords' : IDL.Func([], [IDL.Vec(SaleRecord)], ['query']),
    'getSalesFeedbackLog' : IDL.Func([], [IDL.Vec(SalesFeedback)], ['query']),
    'getSavedProperties' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscriptionStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getValuationReportsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ValuationReport)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isIntelligenceSeeded' : IDL.Func([], [IDL.Bool], ['query']),
    'isPremiumUser' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithEmail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'markLeadContacted' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'publishListing' : IDL.Func([IDL.Nat], [], []),
    'recordDailySnapshot' : IDL.Func([IDL.Text], [IDL.Text], []),
    'registerBankOfficer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerWithEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'rejectBankOfficer' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'runValidationTests' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveAILearningSubmission' : IDL.Func([AILearningInput], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProperty' : IDL.Func([IDL.Nat], [], []),
    'searchListings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'searchLocalities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'seedAndRetrain' : IDL.Func([IDL.Vec(ReraProject)], [IDL.Bool], []),
    'seedIntelligenceData' : IDL.Func([], [], []),
    'setStripeConfig' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'submitLead' : IDL.Func([LeadInput], [IDL.Text], []),
    'submitManualProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitSaleFeedback' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'submitSaleRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'submitValuation' : IDL.Func(
        [ValuationRequest],
        [ValuationResult],
        ['query'],
      ),
    'trackFeedback' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unsaveProperty' : IDL.Func([IDL.Nat], [], []),
    'updateConfidence' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'updateDemandSignals' : IDL.Func([], [IDL.Text], []),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateReraProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateSubscriptionStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'verifyAndUpgradeFromSession' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };