/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ValuationRequest {
    age: bigint;
    propertyType: string;
    sqft: bigint;
    builderName?: string;
    apartmentSubType?: ApartmentSubType;
    locality: string;
    amenitiesCount: bigint;
}
export type Time = bigint;
export interface ManualProjectEntry {
    name: string;
    submittedAt: bigint;
    submittedBy: string;
    locality: string;
}
export interface ValuationResponse {
    breakdown: ValuationBreakdown;
    confidenceReason: string;
    bestPrice: bigint;
    priceMax: bigint;
    priceMin: bigint;
    confidence: bigint;
    localityFound: boolean;
}
export interface PropertyListing {
    id: bigint;
    bhk: bigint;
    floor: bigint;
    status: ListingStatus;
    totalFloors: bigint;
    title: string;
    projectName: string;
    propertyType: PropertyType;
    city: string;
    createdAt: Time;
    badges: Array<string>;
    carpetArea: bigint;
    builderName: string;
    builtUpArea: bigint;
    description: string;
    openParking: bigint;
    legalStatus: string;
    mediaBlobs: Array<ExternalBlob>;
    coveredParking: bigint;
    buildingAge: bigint;
    sellerId: Principal;
    balconies: bigint;
    price: bigint;
    facing: string;
    location: string;
    plotArea: bigint;
    reraNumber: string;
    landUse: string;
    plotUnit: string;
}
export interface LeadInput {
    service_type: string;
    is_priority: boolean;
    name: string;
    email: string;
    message: string;
    phone: string;
    budget: string;
    location: string;
}
export interface LeadFilter {
    date_to?: bigint;
    service_type?: string;
    date_from?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ValuationBreakdown {
    comparablesUsed: bigint;
    pricePerSqft: bigint;
    infraContribution: bigint;
    metroContribution: bigint;
    locationContribution: bigint;
    demandContribution: bigint;
    comparablesContribution: bigint;
}
export interface Lead {
    id: string;
    service_type: string;
    is_priority: boolean;
    name: string;
    created_at: bigint;
    email: string;
    message: string;
    phone: string;
    budget: string;
    location: string;
    is_contacted: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SaleRecord {
    propertyType: string;
    sqft: bigint;
    soldPrice: bigint;
    timestamp: bigint;
    locality: string;
}
export interface PriceSnapshot {
    source: string;
    pricePerSqft: bigint;
    confidenceWeight: bigint;
    timestamp: bigint;
    locality: string;
}
export interface SalesFeedback {
    actualPrice: bigint;
    predictedPrice: bigint;
    timestamp: bigint;
    locality: string;
}
export interface LocalityIntelligence {
    amenitiesScore: bigint;
    city: string;
    name: string;
    avgPricePerSqft: bigint;
    demandScore: bigint;
    infraScore: bigint;
    locationScore: bigint;
    rentalPerSqft: bigint;
    growthRate: bigint;
    supplyDensity: bigint;
}
export interface AILearningInput {
    propertyType: string;
    area: number;
    date: string;
    soldPrice: number;
    notes: string;
    locality: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DemandSignal {
    source: string;
    demandScore: bigint;
    timestamp: bigint;
    locality: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ReraProject {
    status: string;
    possessionDate: string;
    projectName: string;
    propertyType: string;
    builderName: string;
    microLocation: string;
    dataType: string;
    priceMax: bigint;
    priceMin: bigint;
    locality: string;
    unitSize: bigint;
}
export interface Enquiry {
    id: bigint;
    projectName: string;
    name: string;
    createdAt: Time;
    projectId: string;
    phone: string;
}
export interface DealScoreResponse {
    fairValue: bigint;
    expectedDaysToSell: bigint;
    demandScore: bigint;
    liquidityScore: bigint;
    dealTag: string;
    priceGap: bigint;
    dealScore: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface ValuationResult {
    comparablesUsed: bigint;
    subTypeMultiplier: bigint;
    pricePerSqft: bigint;
    infraContribution: bigint;
    metroContribution: bigint;
    locationContribution: bigint;
    confidenceReason: string;
    subTypeApplied: string;
    builderApplied: string;
    demandContribution: bigint;
    bestPrice: bigint;
    comparablesContribution: bigint;
    priceMax: bigint;
    priceMin: bigint;
    confidence: bigint;
    localityFound: boolean;
    builderMultiplier: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ForecastResponse {
    conservative: bigint;
    aggressive: bigint;
    realistic: bigint;
    disclaimer: string;
    basePrice: bigint;
    growthRate: bigint;
}
export interface AILearningSubmission {
    id: bigint;
    propertyType: string;
    area: number;
    date: string;
    submittedAt: bigint;
    soldPrice: number;
    notes: string;
    locality: string;
}
export interface MetroInfo {
    nearestStation: string;
    distanceKm: string;
    hasMetro: boolean;
    metroScore: bigint;
}
export interface RentalResponse {
    avgRentPerSqft: bigint;
    yieldPercent: bigint;
    avgRent: bigint;
    rentMax: bigint;
    rentMin: bigint;
    rentalConfidence: bigint;
    vacancyRate: bigint;
}
export interface BankerApplication {
    id: bigint;
    org: string;
    status: BankerStatus;
    appliedAt: bigint;
    principal: Principal;
    city: string;
    name: string;
    reviewNote: string;
    reviewedAt?: bigint;
    email: string;
    mobile: string;
}
export interface ValuationReport {
    id: bigint;
    propertyType: PropertyType;
    userId: Principal;
    createdAt: Time;
    estimatedMax: bigint;
    estimatedMin: bigint;
    confidence: bigint;
    location: string;
}
export interface UserProfile {
    password_hash?: string;
    username: string;
    city: string;
    role: UserRole;
    fullName: string;
    auth_provider?: string;
    email: string;
    email_hash?: string;
    panNumber: string;
    subscription_status: string;
    mobile: string;
}
export enum ApartmentSubType {
    township = "township",
    gated = "gated",
    standalone = "standalone",
    unknown_ = "unknown"
}
export enum BankerStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ListingStatus {
    published = "published",
    draft = "draft"
}
export enum PropertyType {
    villa = "villa",
    flat = "flat",
    plot = "plot"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addNewReraProjects(newProjects: Array<ReraProject>): Promise<boolean>;
    addPriceSnapshot(locality: string, price: bigint): Promise<string>;
    addValuationReport(location: string, propertyType: PropertyType, estimatedMin: bigint, estimatedMax: bigint, confidence: bigint): Promise<bigint>;
    approveBankOfficer(id: bigint, note: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanupOldData(maxAgeDays: bigint): Promise<string>;
    computeValuation(locality: string, propertyType: string, sqft: bigint, age: bigint, amenitiesCount: bigint): Promise<ValuationResponse>;
    createCheckoutSession(): Promise<string>;
    createEnquiry(projectId: string, projectName: string, name: string, phone: string): Promise<bigint>;
    createListing(title: string, propertyType: PropertyType, location: string, city: string, price: bigint, carpetArea: bigint, builtUpArea: bigint, bhk: bigint, floor: bigint, totalFloors: bigint, buildingAge: bigint, facing: string, coveredParking: bigint, openParking: bigint, balconies: bigint, builderName: string, projectName: string, reraNumber: string, legalStatus: string, landUse: string, plotArea: bigint, plotUnit: string, badges: Array<string>, mediaBlobs: Array<ExternalBlob>, description: string): Promise<bigint>;
    deleteListing(listingId: bigint): Promise<void>;
    filterListings(propertyType: PropertyType, minPrice: bigint, maxPrice: bigint, bhk: bigint): Promise<Array<PropertyListing>>;
    getAILearningSubmissions(): Promise<Array<AILearningSubmission>>;
    getAllBankerApps(): Promise<Array<BankerApplication>>;
    getAllPublishedListings(): Promise<Array<PropertyListing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDealScore(listingId: bigint): Promise<DealScoreResponse>;
    getDemandSignals(locality: string): Promise<Array<DemandSignal>>;
    getEnquiries(): Promise<Array<Enquiry>>;
    getFeedbackCount(): Promise<bigint>;
    getForecast(locality: string, propertyType: string): Promise<ForecastResponse>;
    getLeads(filter: LeadFilter): Promise<Array<Lead>>;
    getListingById(listingId: bigint): Promise<PropertyListing | null>;
    getListingsBySeller(sellerId: Principal): Promise<Array<PropertyListing>>;
    getLocalityIntelligence(locality: string): Promise<LocalityIntelligence | null>;
    getLocalityList(): Promise<Array<string>>;
    getManualProjects(locality: string): Promise<Array<ManualProjectEntry>>;
    getMetroInfo(locality: string): Promise<MetroInfo>;
    getMyBankerStatus(): Promise<string>;
    getPendingBankers(): Promise<Array<BankerApplication>>;
    getPriceHistory(locality: string): Promise<Array<PriceSnapshot>>;
    getRentalIntelligence(locality: string): Promise<RentalResponse>;
    getReraProjects(): Promise<Array<ReraProject>>;
    getSaleRecords(): Promise<Array<SaleRecord>>;
    getSalesFeedbackLog(): Promise<Array<SalesFeedback>>;
    getSavedProperties(): Promise<Array<PropertyListing>>;
    getStripeSessionStatus(sessionId: string): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSubscriptionStatus(): Promise<string>;
    getValuationReportsForUser(userId: Principal): Promise<Array<ValuationReport>>;
    isCallerAdmin(): Promise<boolean>;
    isIntelligenceSeeded(): Promise<boolean>;
    isPremiumUser(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    loginWithEmail(emailHash: string, passwordHash: string): Promise<UserProfile | null>;
    markLeadContacted(leadId: string): Promise<boolean>;
    publishListing(listingId: bigint): Promise<void>;
    recordDailySnapshot(locality: string): Promise<string>;
    registerBankOfficer(name: string, email: string, mobile: string, org: string, city: string): Promise<bigint>;
    registerUser(username: string, fullName: string, mobile: string, email: string, city: string, panNumber: string): Promise<void>;
    registerWithEmail(emailHash: string, passwordHash: string, name: string): Promise<string>;
    rejectBankOfficer(id: bigint, note: string): Promise<boolean>;
    runValidationTests(): Promise<Array<string>>;
    saveAILearningSubmission(input: AILearningInput): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProperty(listingId: bigint): Promise<void>;
    searchListings(location: string): Promise<Array<PropertyListing>>;
    searchLocalities(searchQuery: string): Promise<Array<string>>;
    seedAndRetrain(newProjects: Array<ReraProject>): Promise<boolean>;
    seedIntelligenceData(): Promise<void>;
    setStripeConfig(secretKey: string, priceInCents: bigint, allowedCountries: Array<string>): Promise<void>;
    setStripeConfiguration(secretKey: string, priceInCents: bigint, allowedCountries: Array<string>): Promise<void>;
    submitLead(input: LeadInput): Promise<string>;
    submitManualProject(name: string, locality: string): Promise<void>;
    submitSaleFeedback(locality: string, predictedPrice: bigint, actualPrice: bigint): Promise<string>;
    submitSaleRecord(locality: string, sqft: bigint, propertyType: string, soldPrice: bigint): Promise<string>;
    /**
     * / Extended valuation endpoint — accepts ValuationRequest, returns ValuationResult.
     * / Uses the same core engine as computeValuation but layers in:
     * /   1. Builder premium multiplier (clamped 0.90–1.40)
     * /   2. Apartment sub-type multiplier (standalone < gated < township)
     */
    submitValuation(req: ValuationRequest): Promise<ValuationResult>;
    trackFeedback(listingId: bigint, eventType: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unsaveProperty(listingId: bigint): Promise<void>;
    updateConfidence(locality: string, source: string, actualPrice: bigint): Promise<string>;
    updateDemandSignals(): Promise<string>;
    updateListing(listingId: bigint, title: string, propertyType: PropertyType, location: string, city: string, price: bigint, carpetArea: bigint, builtUpArea: bigint, bhk: bigint, floor: bigint, totalFloors: bigint, buildingAge: bigint, facing: string, coveredParking: bigint, openParking: bigint, balconies: bigint, builderName: string, projectName: string, reraNumber: string, legalStatus: string, landUse: string, plotArea: bigint, plotUnit: string, badges: Array<string>, mediaBlobs: Array<ExternalBlob>, description: string): Promise<void>;
    updateReraProject(key: string, updatedStatus: string, updatedPossessionDate: string, updatedPriceMin: bigint, updatedPriceMax: bigint): Promise<boolean>;
    updateSubscriptionStatus(userId: string, status: string): Promise<boolean>;
    updateUserRole(user: Principal, role: UserRole): Promise<void>;
    verifyAndUpgradeFromSession(sessionId: string): Promise<string>;
}
import type { ApartmentSubType as _ApartmentSubType, BankerApplication as _BankerApplication, BankerStatus as _BankerStatus, ExternalBlob as _ExternalBlob, LeadFilter as _LeadFilter, ListingStatus as _ListingStatus, LocalityIntelligence as _LocalityIntelligence, PropertyListing as _PropertyListing, PropertyType as _PropertyType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, ValuationReport as _ValuationReport, ValuationRequest as _ValuationRequest, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addNewReraProjects(arg0: Array<ReraProject>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewReraProjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewReraProjects(arg0);
            return result;
        }
    }
    async addPriceSnapshot(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPriceSnapshot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPriceSnapshot(arg0, arg1);
            return result;
        }
    }
    async addValuationReport(arg0: string, arg1: PropertyType, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addValuationReport(arg0, to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addValuationReport(arg0, to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async approveBankOfficer(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBankOfficer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBankOfficer(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cleanupOldData(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupOldData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupOldData(arg0);
            return result;
        }
    }
    async computeValuation(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<ValuationResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.computeValuation(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeValuation(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createCheckoutSession(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession();
            return result;
        }
    }
    async createEnquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEnquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEnquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createListing(arg0: string, arg1: PropertyType, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: bigint, arg10: bigint, arg11: string, arg12: bigint, arg13: bigint, arg14: bigint, arg15: string, arg16: string, arg17: string, arg18: string, arg19: string, arg20: bigint, arg21: string, arg22: Array<string>, arg23: Array<ExternalBlob>, arg24: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg23), arg24);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg23), arg24);
            return result;
        }
    }
    async deleteListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async filterListings(arg0: PropertyType, arg1: bigint, arg2: bigint, arg3: bigint): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListings(to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListings(to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAILearningSubmissions(): Promise<Array<AILearningSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAILearningSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAILearningSubmissions();
            return result;
        }
    }
    async getAllBankerApps(): Promise<Array<BankerApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankerApps();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankerApps();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublishedListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedListings();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedListings();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDealScore(arg0: bigint): Promise<DealScoreResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getDealScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDealScore(arg0);
            return result;
        }
    }
    async getDemandSignals(arg0: string): Promise<Array<DemandSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemandSignals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemandSignals(arg0);
            return result;
        }
    }
    async getEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiries();
            return result;
        }
    }
    async getFeedbackCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackCount();
            return result;
        }
    }
    async getForecast(arg0: string, arg1: string): Promise<ForecastResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getForecast(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForecast(arg0, arg1);
            return result;
        }
    }
    async getLeads(arg0: LeadFilter): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads(to_candid_LeadFilter_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads(to_candid_LeadFilter_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getListingById(arg0: bigint): Promise<PropertyListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsBySeller(arg0: Principal): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsBySeller(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsBySeller(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocalityIntelligence(arg0: string): Promise<LocalityIntelligence | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalityIntelligence(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalityIntelligence(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocalityList(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalityList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalityList();
            return result;
        }
    }
    async getManualProjects(arg0: string): Promise<Array<ManualProjectEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualProjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualProjects(arg0);
            return result;
        }
    }
    async getMetroInfo(arg0: string): Promise<MetroInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetroInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetroInfo(arg0);
            return result;
        }
    }
    async getMyBankerStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBankerStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBankerStatus();
            return result;
        }
    }
    async getPendingBankers(): Promise<Array<BankerApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingBankers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingBankers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceHistory(arg0: string): Promise<Array<PriceSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceHistory(arg0);
            return result;
        }
    }
    async getRentalIntelligence(arg0: string): Promise<RentalResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getRentalIntelligence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRentalIntelligence(arg0);
            return result;
        }
    }
    async getReraProjects(): Promise<Array<ReraProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReraProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReraProjects();
            return result;
        }
    }
    async getSaleRecords(): Promise<Array<SaleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaleRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaleRecords();
            return result;
        }
    }
    async getSalesFeedbackLog(): Promise<Array<SalesFeedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesFeedbackLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesFeedbackLog();
            return result;
        }
    }
    async getSavedProperties(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedProperties();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedProperties();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubscriptionStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubscriptionStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubscriptionStatus();
            return result;
        }
    }
    async getValuationReportsForUser(arg0: Principal): Promise<Array<ValuationReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValuationReportsForUser(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValuationReportsForUser(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isIntelligenceSeeded(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isIntelligenceSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isIntelligenceSeeded();
            return result;
        }
    }
    async isPremiumUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPremiumUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPremiumUser();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async loginWithEmail(arg0: string, arg1: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithEmail(arg0, arg1);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithEmail(arg0, arg1);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async markLeadContacted(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markLeadContacted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLeadContacted(arg0);
            return result;
        }
    }
    async publishListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishListing(arg0);
            return result;
        }
    }
    async recordDailySnapshot(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDailySnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDailySnapshot(arg0);
            return result;
        }
    }
    async registerBankOfficer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBankOfficer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBankOfficer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerWithEmail(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithEmail(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithEmail(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectBankOfficer(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBankOfficer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBankOfficer(arg0, arg1);
            return result;
        }
    }
    async runValidationTests(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.runValidationTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runValidationTests();
            return result;
        }
    }
    async saveAILearningSubmission(arg0: AILearningInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAILearningSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAILearningSubmission(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProperty(arg0);
            return result;
        }
    }
    async searchListings(arg0: string): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchLocalities(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLocalities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLocalities(arg0);
            return result;
        }
    }
    async seedAndRetrain(arg0: Array<ReraProject>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.seedAndRetrain(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedAndRetrain(arg0);
            return result;
        }
    }
    async seedIntelligenceData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedIntelligenceData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedIntelligenceData();
            return result;
        }
    }
    async setStripeConfig(arg0: string, arg1: bigint, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfig(arg0, arg1, arg2);
            return result;
        }
    }
    async setStripeConfiguration(arg0: string, arg1: bigint, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0, arg1, arg2);
            return result;
        }
    }
    async submitLead(arg0: LeadInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(arg0);
            return result;
        }
    }
    async submitManualProject(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitManualProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitManualProject(arg0, arg1);
            return result;
        }
    }
    async submitSaleFeedback(arg0: string, arg1: bigint, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSaleFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSaleFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async submitSaleRecord(arg0: string, arg1: bigint, arg2: string, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSaleRecord(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSaleRecord(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitValuation(arg0: ValuationRequest): Promise<ValuationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitValuation(to_candid_ValuationRequest_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitValuation(to_candid_ValuationRequest_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async trackFeedback(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackFeedback(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unsaveProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveProperty(arg0);
            return result;
        }
    }
    async updateConfidence(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConfidence(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConfidence(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDemandSignals(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDemandSignals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDemandSignals();
            return result;
        }
    }
    async updateListing(arg0: bigint, arg1: string, arg2: PropertyType, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: bigint, arg10: bigint, arg11: bigint, arg12: string, arg13: bigint, arg14: bigint, arg15: bigint, arg16: string, arg17: string, arg18: string, arg19: string, arg20: string, arg21: bigint, arg22: string, arg23: Array<string>, arg24: Array<ExternalBlob>, arg25: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg24), arg25);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, to_candid_PropertyType_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg24), arg25);
            return result;
        }
    }
    async updateReraProject(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReraProject(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReraProject(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateSubscriptionStatus(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0, arg1);
            return result;
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyAndUpgradeFromSession(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndUpgradeFromSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndUpgradeFromSession(arg0);
            return result;
        }
    }
}
function from_candid_BankerApplication_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankerApplication): BankerApplication {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_BankerStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankerStatus): BankerStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_PropertyListing_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListing): Promise<PropertyListing> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ValuationReport_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValuationReport): ValuationReport {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PropertyListing]): Promise<PropertyListing | null> {
    return value.length === 0 ? null : await from_candid_PropertyListing_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocalityIntelligence]): LocalityIntelligence | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bhk: bigint;
    floor: bigint;
    status: _ListingStatus;
    totalFloors: bigint;
    title: string;
    projectName: string;
    propertyType: _PropertyType;
    city: string;
    createdAt: _Time;
    badges: Array<string>;
    carpetArea: bigint;
    builderName: string;
    builtUpArea: bigint;
    description: string;
    openParking: bigint;
    legalStatus: string;
    mediaBlobs: Array<_ExternalBlob>;
    coveredParking: bigint;
    buildingAge: bigint;
    sellerId: Principal;
    balconies: bigint;
    price: bigint;
    facing: string;
    location: string;
    plotArea: bigint;
    reraNumber: string;
    landUse: string;
    plotUnit: string;
}): Promise<{
    id: bigint;
    bhk: bigint;
    floor: bigint;
    status: ListingStatus;
    totalFloors: bigint;
    title: string;
    projectName: string;
    propertyType: PropertyType;
    city: string;
    createdAt: Time;
    badges: Array<string>;
    carpetArea: bigint;
    builderName: string;
    builtUpArea: bigint;
    description: string;
    openParking: bigint;
    legalStatus: string;
    mediaBlobs: Array<ExternalBlob>;
    coveredParking: bigint;
    buildingAge: bigint;
    sellerId: Principal;
    balconies: bigint;
    price: bigint;
    facing: string;
    location: string;
    plotArea: bigint;
    reraNumber: string;
    landUse: string;
    plotUnit: string;
}> {
    return {
        id: value.id,
        bhk: value.bhk,
        floor: value.floor,
        status: from_candid_ListingStatus_n17(_uploadFile, _downloadFile, value.status),
        totalFloors: value.totalFloors,
        title: value.title,
        projectName: value.projectName,
        propertyType: from_candid_PropertyType_n19(_uploadFile, _downloadFile, value.propertyType),
        city: value.city,
        createdAt: value.createdAt,
        badges: value.badges,
        carpetArea: value.carpetArea,
        builderName: value.builderName,
        builtUpArea: value.builtUpArea,
        description: value.description,
        openParking: value.openParking,
        legalStatus: value.legalStatus,
        mediaBlobs: await from_candid_vec_n21(_uploadFile, _downloadFile, value.mediaBlobs),
        coveredParking: value.coveredParking,
        buildingAge: value.buildingAge,
        sellerId: value.sellerId,
        balconies: value.balconies,
        price: value.price,
        facing: value.facing,
        location: value.location,
        plotArea: value.plotArea,
        reraNumber: value.reraNumber,
        landUse: value.landUse,
        plotUnit: value.plotUnit
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    org: string;
    status: _BankerStatus;
    appliedAt: bigint;
    principal: Principal;
    city: string;
    name: string;
    reviewNote: string;
    reviewedAt: [] | [bigint];
    email: string;
    mobile: string;
}): {
    id: bigint;
    org: string;
    status: BankerStatus;
    appliedAt: bigint;
    principal: Principal;
    city: string;
    name: string;
    reviewNote: string;
    reviewedAt?: bigint;
    email: string;
    mobile: string;
} {
    return {
        id: value.id,
        org: value.org,
        status: from_candid_BankerStatus_n26(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        principal: value.principal,
        city: value.city,
        name: value.name,
        reviewNote: value.reviewNote,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.reviewedAt)),
        email: value.email,
        mobile: value.mobile
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password_hash: [] | [string];
    username: string;
    city: string;
    role: _UserRole;
    fullName: string;
    auth_provider: [] | [string];
    email: string;
    email_hash: [] | [string];
    panNumber: string;
    subscription_status: string;
    mobile: string;
}): {
    password_hash?: string;
    username: string;
    city: string;
    role: UserRole;
    fullName: string;
    auth_provider?: string;
    email: string;
    email_hash?: string;
    panNumber: string;
    subscription_status: string;
    mobile: string;
} {
    return {
        password_hash: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.password_hash)),
        username: value.username,
        city: value.city,
        role: from_candid_UserRole_n33(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        auth_provider: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.auth_provider)),
        email: value.email,
        email_hash: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.email_hash)),
        panNumber: value.panNumber,
        subscription_status: value.subscription_status,
        mobile: value.mobile
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    propertyType: _PropertyType;
    userId: Principal;
    createdAt: _Time;
    estimatedMax: bigint;
    estimatedMin: bigint;
    confidence: bigint;
    location: string;
}): {
    id: bigint;
    propertyType: PropertyType;
    userId: Principal;
    createdAt: Time;
    estimatedMax: bigint;
    estimatedMin: bigint;
    confidence: bigint;
    location: string;
} {
    return {
        id: value.id,
        propertyType: from_candid_PropertyType_n19(_uploadFile, _downloadFile, value.propertyType),
        userId: value.userId,
        createdAt: value.createdAt,
        estimatedMax: value.estimatedMax,
        estimatedMin: value.estimatedMin,
        confidence: value.confidence,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): ListingStatus {
    return "published" in value ? ListingStatus.published : "draft" in value ? ListingStatus.draft : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    villa: null;
} | {
    flat: null;
} | {
    plot: null;
}): PropertyType {
    return "villa" in value ? PropertyType.villa : "flat" in value ? PropertyType.flat : "plot" in value ? PropertyType.plot : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BankerStatus {
    return "pending" in value ? BankerStatus.pending : "approved" in value ? BankerStatus.approved : "rejected" in value ? BankerStatus.rejected : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyListing>): Promise<Array<PropertyListing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PropertyListing_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BankerApplication>): Array<BankerApplication> {
    return value.map((x)=>from_candid_BankerApplication_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ValuationReport>): Array<ValuationReport> {
    return value.map((x)=>from_candid_ValuationReport_n40(_uploadFile, _downloadFile, x));
}
function to_candid_ApartmentSubType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApartmentSubType): _ApartmentSubType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LeadFilter_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadFilter): _LeadFilter {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ValuationRequest_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ValuationRequest): _ValuationRequest {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date_to?: bigint;
    service_type?: string;
    date_from?: bigint;
}): {
    date_to: [] | [bigint];
    service_type: [] | [string];
    date_from: [] | [bigint];
} {
    return {
        date_to: value.date_to ? candid_some(value.date_to) : candid_none(),
        service_type: value.service_type ? candid_some(value.service_type) : candid_none(),
        date_from: value.date_from ? candid_some(value.date_from) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password_hash?: string;
    username: string;
    city: string;
    role: UserRole;
    fullName: string;
    auth_provider?: string;
    email: string;
    email_hash?: string;
    panNumber: string;
    subscription_status: string;
    mobile: string;
}): {
    password_hash: [] | [string];
    username: string;
    city: string;
    role: _UserRole;
    fullName: string;
    auth_provider: [] | [string];
    email: string;
    email_hash: [] | [string];
    panNumber: string;
    subscription_status: string;
    mobile: string;
} {
    return {
        password_hash: value.password_hash ? candid_some(value.password_hash) : candid_none(),
        username: value.username,
        city: value.city,
        role: to_candid_UserRole_n10(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        auth_provider: value.auth_provider ? candid_some(value.auth_provider) : candid_none(),
        email: value.email,
        email_hash: value.email_hash ? candid_some(value.email_hash) : candid_none(),
        panNumber: value.panNumber,
        subscription_status: value.subscription_status,
        mobile: value.mobile
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    propertyType: string;
    sqft: bigint;
    builderName?: string;
    apartmentSubType?: ApartmentSubType;
    locality: string;
    amenitiesCount: bigint;
}): {
    age: bigint;
    propertyType: string;
    sqft: bigint;
    builderName: [] | [string];
    apartmentSubType: [] | [_ApartmentSubType];
    locality: string;
    amenitiesCount: bigint;
} {
    return {
        age: value.age,
        propertyType: value.propertyType,
        sqft: value.sqft,
        builderName: value.builderName ? candid_some(value.builderName) : candid_none(),
        apartmentSubType: value.apartmentSubType ? candid_some(to_candid_ApartmentSubType_n46(_uploadFile, _downloadFile, value.apartmentSubType)) : candid_none(),
        locality: value.locality,
        amenitiesCount: value.amenitiesCount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApartmentSubType): {
    township: null;
} | {
    gated: null;
} | {
    standalone: null;
} | {
    unknown: null;
} {
    return value == ApartmentSubType.township ? {
        township: null
    } : value == ApartmentSubType.gated ? {
        gated: null
    } : value == ApartmentSubType.standalone ? {
        standalone: null
    } : value == ApartmentSubType.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    villa: null;
} | {
    flat: null;
} | {
    plot: null;
} {
    return value == PropertyType.villa ? {
        villa: null
    } : value == PropertyType.flat ? {
        flat: null
    } : value == PropertyType.plot ? {
        plot: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
